### ISSUE TITLE
base_connection.buffer is a list of bytes, rather than a bytes

### ISSUE THREAD

**Issue by gappleto97** [p2p-today/p2p-project#117]
For context, see end of #116

**Comment by the-zebulan** [comment]
Ok, looks like I have some reading to do on bytes. Do you mean replace it with a `bytearray`?

**Comment by gappleto97** [comment]
That could also work. The only real difference is that `bytearray` is mutable, if I remember right. There may be some more subtle differences that I don't remember, though. 

Assuming it doesn't cause bugs I wouldn't expect, `bytearray` looks safer to me. I'm much more comfortable directly modifying an object than reassigning it. And while that's not terribly rational in Python, it's a habit that's stuck with me. `bytearray.append` will probably be your friend.

**Comment by the-zebulan** [comment]
Ok, thanks for the tip. Ya, it looks like `bytes` is immutable and `bytesarray` is mutable (append and such). I was just looking at the `base_connection` code and saw `self.buffer.append(data)` so that's why I asked about `bytesarray`.

I'm just about to head to bed but I will mess around with it in the morning and try to get it working!

**Comment by gappleto97** [comment]
Just tinkered around a little. 

There are going to be two things of note, it looks like. 

1. Python 3 is more restrictive here than python 2. You'll probably want to test in there before anything else

2. You want `bytearray.extend`, not `bytearray.append`. And you want to use array slicing rather than pop. So: `bytes(barray[0:x])`

**Comment by the-zebulan** [comment]
Interesting. Ok, thanks for the tips!
