### ISSUE TITLE
is this project similar to: pyp2p ?

### ISSUE THREAD

**Issue by Kentoseth** [p2p-today/p2p-project#153]
I have been having a discussion with the author of: [pyp2p](https://github.com/StorjOld/pyp2p)

The discussion is here: [https://github.com/StorjOld/pyp2p/issues/42](https://github.com/StorjOld/pyp2p/issues/42)

Are these 2 projects similar, in that I wish to create a bitcoin-like networking layer, where a message is broadcast from 1 node to all other nodes?

**Comment by LivInTheLookingGlass** [comment]
I have similar caveats to what the other dev was saying, but yes, you could do this.

The advantage to mine in particular is that (with a bit of effort) you could have browsers communicate this to the whole network as well, with a relay.

The idea would go roughly:

* there's a network of Python and Node.js nodes using TCP or TLS
* there's an overlapping set of Node.js nodes using websockets
* that overlapping set echoes the broadcasts of one network to the other (and does not for whispers)
* browsers talk to the Node.js nodes which use websockets (since they can neither listen themselves, nor use TCP/TLS).

The big caveat here is that I'm planning to reimplement this in the next year or so. The way I designed it didn't meet a couple of my goals. Namely, the distributed hash table template I gave is very inefficient, and the design is very difficult in statically typed languages.

**Comment by LivInTheLookingGlass** [comment]
Actually, if you go back in my documentation from older versions, I think I even used this as an example, using the pycoin library.

These days I imagine you'd use bit instead.

**Comment by Kentoseth** [comment]
> Actually, if you go back in my documentation from older versions, I think I even used this as an example, using the pycoin library.

Can you share the link to the example?

I would be eager to attempt using this lib (as it seems more frequently maintained/updated). You mentioned that something similar could be achieved with this lib (as pyp2p does), so I would like to reference that example and attempt building my own PoC.

Thanks for your responses so far.

**Comment by LivInTheLookingGlass** [comment]
Turns out that I did not use this as an example. I think people told me it was confusing, and I removed it. You want something like [the first example in Advanced Usage](http://v0-6.p2p.today/python/tutorial/mesh.html).
