### ISSUE TITLE
Automatically finding Nodes

### ISSUE THREAD

**Issue by Kentoseth** [p2p-today/p2p-project#155]
As per my discussion here: https://github.com/p2p-today/p2p-project/issues/153

Which discussed this repo: https://github.com/StorjOld/pyp2p

It looks like that project supports automatically finding/removing nodes from the network.

From the Mesh example on the docs:

```
sock = mesh.MeshSocket('0.0.0.0', 4444)
sock.connect('192.168.1.14', 4567)
```

It looks like one needs to manually connect to new nodes. Can you confirm?

**Comment by LivInTheLookingGlass** [comment]
Okay, so there are two ways that you can find your network.

1. You can use the `py2p.bootstrap` method, which connects to a DHT and tries to find your network there, AND/OR
2. You can supply a short list of nodes that you think will be online, and it will discover the rest from there

At the moment 1 does not work because it requires me to host parts of the DHT. I could start doing this again if I knew people would be using it, but this project saw very little usage for that time so I stopped running it.
