### ISSUE TITLE
Improve CodeClimate score

### ISSUE THREAD

**Issue by gappleto97** [p2p-today/p2p-project#92]
I'd love it if we could get all code that isn't _really_ an issue to not trigger an error, and refactor the rest.

**Comment by the-zebulan** [comment]
@gappleto97 ,

I saw your message on /r/Python mentioning this repo. I looked at the CodeClimate score and noticed there were a few Python files that seem to have some PEP8 style issues (lines too long, indentation, etc). I think that's what you mean by "code that isn't really an issue" right?

Would it be ok for me to just try and get rid of those PEP8 style issues? I know it doesn't resolve this whole issue but it might help the CodeClimate score a bit.

**Comment by gappleto97** [comment]
If you want to hammer those issues out I'm more than behind you there. A lot of the issues on CodeClimate are just "shove this into another method" or "this conditional is ridiculous". 

I think you might have meant to just blacklist some issues though, and I'm not a huge fan of that. If there's a flaw, I'd rather know about it.

**Comment by the-zebulan** [comment]
@gappleto97 ,

Just to clarify, I didn't want to blacklist or disable any issues, I just wanted to fix the PEP8 style issues. Some of the other issues seemed a bit more complicated and I didn't want to make any big changes since I don't fully understand the whole repo (I'm maybe an intermediate Python programmer?).

I've fixed most if not all of the PEP8 issues on `chord.py` but I thought it would be better if you approve of certain style choices before I go on to do the other Python files. I'll send the PR right away but I will add the other files to that PR if you approve of the type of changes in the first file.
